export const db = {
  all_news: [
    {
      id: 1,
      title:
        "Cake meme reflects coronavirus absurdity in a world where nothing is what it seems",
      description:
        "Earlier this month, a viral video depicting hyper-realistic cakes as everyday items had folks on social media double-guessing every other post, and sometimes even their own realities, effectively launching the next meme : “Is this real or is this cake?”",
      author: "Lucy Hiddleston",
      reading_time: 4,
      date: "05/08/22",
      trending: true,
      breaking_news: false,
      editors_pick: false,
      likes: 0,
      share: 0,
      image_url: "./src/images/posts/lemon.png",
      image_alt: "Imagem de um limão com terra",
      topic: "corona",
    },
    {
      id: 2,
      title:
        "John Lewis to make final journey across Edmund Pettus Bridge in procession",
      description:
        "The body of the late US Rep. John Lewis on Sunday will make the final journey across the famous bridge in Selma, Alabama, where he helped lead a march for voting rights in 1965.",
      author: "Lucy Hiddleston",
      reading_time: 4,
      date: "05/08/22",
      trending: false,
      breaking_news: false,
      editors_pick: false,
      likes: 28,
      share: 72,
      image_url: "./src/images/posts/bridge-man.png",
      image_alt: "Foto de um homem na ponte",
      topic: "history",
    },
    {
      id: 3,
      title:
        "John Lewis, civil rights giant, crosses infamous Selma bridge one final time",
      description:
        "Solemn crowds watch as Lewis, who died earlier this month at the age of 80, is borne by caisson over Edmund Pettus Bridge",
      author: "Caroline Casey",
      reading_time: 4,
      date: "05/08/22",
      trending: false,
      breaking_news: false,
      editors_pick: false,
      likes: 28,
      share: 72,
      image_url: "./src/images/posts/procession.png",
      image_alt: "Imagem de uma procissão",
      topic: "history",
    },
    {
      id: 4,
      title: "Kanye West says he's running for president in 2020.",
      description:
        "Mussum Ipsum, cacilds vidis litro abertis. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.Todo mundo vê os porris que eu tomo, mas ninguém vê os tombis que eu levo!Delegadis gente finis, bibendum egestas augue arcu ut est.",
      author: "Caroline Casey",
      reading_time: 4,
      date: "05/08/22",
      trending: false,
      breaking_news: true,
      editors_pick: false,
      likes: 28,
      share: 72,
      image_url: "./src/images/posts/kanye-west.jpg",
      image_alt: "Imagem de Kanye West",
      topic: "music",
    },
    {
      id: 5,
      title: "Tornado and tide warnings as Storm Hanna lashes Texas",
      description:
        "The body of the late US Rep. John Lewis on Sunday will make the final journey across the famous bridge in Selma, Alabama, where he helped lead a march for voting rights in 1965.",
      author: "Lucy Hiddleston",
      reading_time: 4,
      date: "05/08/22",
      trending: false,
      breaking_news: false,
      editors_pick: false,
      likes: 28,
      share: 72,
      image_url: "./src/images/posts/tornado.png",
      image_alt: "Imagem de um tornado nos EUA",
      topic: "climate",
    },
    {
      id: 6,
      title:
        "20 Years Ago, Steve Jobs Built the ‘Coolest Computer Ever.’ It Bombed",
      description:
        "This month marks the 20th anniversary of the Power Mac G4 Cube, which debuted July 19, 2000. It also marks the 19th anniversary of Apple’s announcement that it was putting the Cube on ice.",
      author: "Lucy Hiddleston",
      reading_time: 4,
      date: "05/08/22",
      trending: false,
      breaking_news: false,
      editors_pick: false,
      likes: 28,
      share: 72,
      image_url: "./src/images/posts/steve-jobs-machine.png",
      image_alt: "Imagem de um computador de Steve Jobs",
      topic: "climate",
    },
    {
      id: 7,
      title:
        "Serological surveys are being conducted to test for coronavirus antibodies. How useful are they?",
      description:
        "The authorities are hoping to find that a substantial proportion of the population has already been infected with the virus – and so is immune.",
      author: "Lucy Hiddleston",
      reading_time: 4,
      date: "05/08/22",
      trending: false,
      breaking_news: false,
      editors_pick: true,
      likes: 28,
      share: 72,
      image_url: "./src/images/posts/corona-test.png",
      image_alt: "Imagem de um teste de coronavírus",
      topic: "corona",
    },
    {
      id: 8,
      title:
        "Making a mark in Asia: East Bengal’s 2003 Asean Cup win – a defining moment for Indian club football",
      description:
        "Beating some of the finest teams from South Asia, East Bengal became the first Indian club to win an officially recognised Asian football tournament.",
      author: "Lucy Hiddleston",
      reading_time: 4,
      date: "05/08/22",
      trending: false,
      breaking_news: false,
      editors_pick: true,
      likes: 28,
      share: 72,
      image_url: "./src/images/posts/football.png",
      image_alt: "Imagem de um time de futebol",
      topic: "sports",
    },
  ],
  live_news: [
    {
      id: 1,
      title: "Beloved Arizona coach loses battle with coronavirus",
      video_cover: "./src/images/live/arizona-man.png",
      video_cover_alt: "Imagem de um senhor do Arizona",
    },
  ],
};
